BEGIN;
DROP TABLE IF EXISTS users,
todos CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(25) NOT NULL,
  email VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);
CREATE TABLE todos(
  id SERIAL PRIMARY KEY,
  user_id INT,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NUll,
  CONSTRAINT fk_todos_users FOREIGN KEY (user_id) REFERENCES users(id)
);
COMMIT;